//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorios
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Consorcio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consorcio()
        {
            this.Gasto = new HashSet<Gasto>();
            this.Unidad = new HashSet<Unidad>();
        }
    
        public int IdConsorcio { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El nombre es requerido")]
        public string Nombre { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "La provincia es requerido")]
        public int IdProvincia { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La ciudad es requerido")]
        public string Ciudad { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La calle es requerido")]
        public string Calle { get; set; }

        [Range(0, int.MaxValue)]
        [Required(ErrorMessage = "La altura es requerido")]
        public int Altura { get; set; }

        [Required(ErrorMessage = "El día de vencimiento es requerido")]
        [Range(1, 28, ErrorMessage = "El día debe estar comprendido entre 1 y 28")]
        public int DiaVencimientoExpensas { get; set; }
        [DataType(DataType.DateTime)]
        public System.DateTime FechaCreacion { get; set; }
        [Range(0, int.MaxValue)]
        public Nullable<int> IdUsuarioCreador { get; set; }
    
        public virtual Provincia Provincia { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unidad> Unidad { get; set; }
    }
}
